<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup Label="Packaging">
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Label="Package Metadata">
    <Version>2.0.19+2.0.18</Version>
    <Authors>Steven T. Cramer</Authors>
    <Company>TimeWarp Enterprises</Company>
    <Description>All of the Tailwind HeroIcons wrapped as Blazor components.</Description>
    <PackageProjectUrl>https://github.com/TimeWarpEngineering/timewarp-heroicons</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TimeWarpEngineering/timewarp-heroicons.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>timewarp; blazor; icons; tailwind; heroicons</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Label="Package Content">
    <None Include="$(RepositoryRoot)assets/logo.png" Pack="true" PackagePath="\" />
    <None Include="$(RepositoryRoot)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>